//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public short CODE { get; set; }
        public short RECIPE_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_IMAGE { get; set; }
        public string AMOUNT { get; set; }
        public Nullable<short> CATEGORY { get; set; }
    
        public virtual RECIPES RECIPES { get; set; }
    }
}
