USE [FINAL_PROJECT]
GO

/****** Object:  Table [dbo].[SAVED_RECIPES]    Script Date: 25/02/2022 13:05:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAVED_RECIPES](
	[MAIL] [varchar](50) NULL,
	[RECIPE_ID] [varchar](30) NOT NULL,
	[RECIPE_TITLE] [varchar](150) NULL,
	[RECIPE_IMAGE] [varchar](150) NULL,
	[RECIPE_SUMMARY] [varchar](max) NULL,
	[READY_IN_MINUTES] [int] NULL,
	[SERVINGS] [int] NULL,
	[NUM_LIKES] [int] NULL,
	[RATING] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[RECIPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAVED_RECIPES]  WITH CHECK ADD  CONSTRAINT [MC] FOREIGN KEY([MAIL])
REFERENCES [dbo].[CLIENTS] ([MAIL])
GO

ALTER TABLE [dbo].[SAVED_RECIPES] CHECK CONSTRAINT [MC]
GO


