USE [FINAL_PROJECT]
GO

/****** Object:  Table [dbo].[SCHEDULES]    Script Date: 12/30/2021 1:39:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SCHEDULES](
	[CODE] [smallint] IDENTITY(1,1) NOT NULL,
	[RECIPE_CODE] [smallint] NOT NULL,
	[DATE] [datetime] NULL,
	[AMOUNT] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCHEDULES]  WITH CHECK ADD FOREIGN KEY([RECIPE_CODE])
REFERENCES [dbo].[RECIPES] ([CODE])
GO


