USE [FINAL_PROJECT]
GO

/****** Object:  Table [dbo].[SAVED_RECIPES]    Script Date: 24/02/2022 15:45:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAVED_RECIPES](
	[MAIL] [varchar](50) NULL,
	[RECIPE_ID] [varchar](30) NOT NULL PRIMARY KEY,
	[RECIPE_TITLE] [varchar](150) NULL,
	[RECIPE_IMAGE] [varchar](150) NULL,
	[RECIPE_SUMMARY] [varchar](max) NULL,
	[READY_IN_MINUTES] [int] NULL,
	[SERVINGS] [int] NULL,
	[NUM_LIKES] [int] NULL,
	[RATING] [float] NULL,
)
GO

ALTER TABLE [dbo].[SAVED_RECIPES]  WITH CHECK ADD  CONSTRAINT [FK_SAVED_RECIPES_CLIENTS] FOREIGN KEY([MAIL])
REFERENCES [dbo].[CLIENTS] ([MAIL])
GO

ALTER TABLE [dbo].[SAVED_RECIPES] CHECK CONSTRAINT [FK_SAVED_RECIPES_CLIENTS]
GO


