USE [FINAL_PROJECT]
GO

/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 16/01/2022 05:47:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTS](
	[CODE] [smallint] IDENTITY(1,1) NOT NULL,
	[RECIPE_CODE] [smallint] NOT NULL,
	[PRODUCT_NAME] [varchar](50) NOT NULL,
	[PRODUCT_IMAGE] [varchar](100) NULL,
	[AMOUNT] [int] NOT NULL,
	[UNIT] [varchar](50) NOT NULL,
	[CATEGORY] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD FOREIGN KEY([RECIPE_CODE])
REFERENCES [dbo].[RECIPES] ([CODE])
GO


