USE [FINAL_PROJECT]
GO

/****** Object:  Table [dbo].[RECIPES]    Script Date: 25/03/2022 14:58:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RECIPES](
	[CODE] [smallint] IDENTITY(1,1) NOT NULL,
	[MAIL] [varchar](50) NULL,
	[RECIPE_ID] [varchar](30) NOT NULL,
	[RECIPE_TITLE] [varchar](150) NULL,
	[RECIPE_IMAGE] [varchar](150) NULL,
	[SCHEDULING_STATUSE] [int] NULL,
	[DATE] [datetime] NOT NULL,
	[COUNT] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RECIPES]  WITH CHECK ADD FOREIGN KEY([MAIL])
REFERENCES [dbo].[CLIENTS] ([MAIL])
GO


